[target.wasm32-unknown-unknown]
runner = "wasm-bindgen-test-runner"
rustflags = [
    "-C",
    "target-feature=+atomics,+bulk-memory",
]

# Only kicks in if actually compiled with unstable compiler.
[unstable]
build-std = ["std,panic_abort"]
