name: Format

on:
  push:
    branches: ["main"]
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  rustfmt:
    name: Rustfmt

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Rust nightly
        run:
          rustup toolchain install nightly --profile minimal --component rustfmt
          --allow-downgrade
      - name: Run Rustfmt
        run: cargo +nightly fmt --check

  taplo:
    name: Taplo

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Restore cached Taplo
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/bin/taplo
          key: taplo
      - name: Install Taplo
        run: cargo install taplo-cli
      - name: Save Taplo to cache
        uses: actions/cache/save@v3
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/bin/taplo
          key: taplo
      - name: Run Taplo
        run: taplo fmt --check
