name: Lint

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  clippy-rustdoc:
    name: Clippy & Rustdoc

    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - wasm32-unknown-unknown

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Rust
        run: rustup target add --target ${{ matrix.target }}
      - name: Run Clippy
        run: cargo clippy --all-targets ${{ matrix.target }} -- -D warnings
      - name: Run Rustdoc
        env:
          RUSTDOCFLAGS: -D warnings
        run:
          cargo doc --no-deps --document-private-items --examples ${{
          matrix.target }}
